apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cemp-local
resources:
  - ../../base
  - ingress.yaml
patches:
  - target:
      kind: Namespace
      name: placeholder
    patch: |
      - op: replace
        path: /metadata/name
        value: cemp-local
  - target:
      kind: PersistentVolumeClaim
      name: mssql-pvc
    patch: |
      - op: replace
        path: /spec/storageClassName
        value: standard
  - target:
      kind: Deployment
      name: cemp-api
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: cemp-api:dev
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
