apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
  namespace: cemp-local
type: Opaque
data:
  SA_PASSWORD: {{ .Values.DB_PASSWORD | default "YourStrongPass123" | toString | b64enc | quote }}
