apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cemp-api-service
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    app: cemp-api
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 1433
      targetPort: 1433
  selector:
    app: mssql
