apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cemp-api-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: cemp-api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    app: cemp-api
    release: {{ .Release.Name }}
