# FROM mcr.microsoft.com/dotnet/aspnet:9.0
# WORKDIR /app
# COPY ./publish .
# ENTRYPOINT ["dotnet", "Employee.API.dll"]

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends libgssapi-krb5-2 && rm -rf /var/lib/apt/lists/*
COPY publish/ .
ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080
ENTRYPOINT ["dotnet","Employee.API.dll"]