FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY src/Employee.API/Employee.API.csproj src/Employee.API/
RUN dotnet restore src/Employee.API/Employee.API.csproj
COPY src/ ./src/
RUN dotnet publish src/Employee.API/Employee.API.csproj -c Release -o /app --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /app .
ENV ASPNETCORE_URLS=http://+:8080
ENTRYPOINT ["dotnet","Employee.API.dll"]