apiVersion: v1
kind: Secret
metadata:
  name: cemp-secret
  namespace: cemp
type: Opaque
data:
  SA_PASSWORD: WW91clN0cm9uZyFQYXNzMTIz
  ConnectionStrings__DefaultConnection: U2VydmVyPW1zc3FsLXNlcnZpY2UsMTQzMztEYXRhYmFzZT1DRU1QO1VzZXIgSWQ9c2E7UGFzc3dvcmQ9WW91clN0cm9uZyFQYXNzMTIzO1RydXN0U2VydmVyQ2VydGlmaWNhdGU9VHJ1ZTs=
  ApiKey: Q2VtcEFQSUtleTIwMjU=
