apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pvc
  namespace: cemp
spec:
  accessModes:
        - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi