version: '3.8'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Pass123"
    ports:
            - "1433:1433"
    volumes:
            - mssql-data:/var/opt/mssql

  cemp-api:
    image: adhivenkatesh7/cemp-api:v2
    depends_on:
            - mssql
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=mssql,1433;Database=CEMP;User Id=sa;Password=YourStrong!Pass123;TrustServerCertificate=True;"
    ports:
            - "8080:80"

volumes:
  mssql-data: