apiVersion: apps/v1
kind: Deployment
metadata:
  name: azurite
  namespace: cemp-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azurite
  template:
    metadata:
      labels:
        app: azurite
    spec:
      containers:
        - name: azurite
          image: mcr.microsoft.com/azure-storage/azurite
          args:
            - azurite
            - --blobHost
            - 0.0.0.0
            - --queueHost
            - 0.0.0.0
            - --tableHost
            - 0.0.0.0
            - --loose
            - --skipApiVersionCheck
          ports:
            - containerPort: 10000
