replicaCount: 2
image:
  repository: adhivenkatesh7/cemp-api
  tag: v16
  pullPolicy: Always
service:
  type: LoadBalancer
  port: 80
env:
  DB_SERVER: "mssql-service"
  DB_DATABASE: "EmployeeDB"
  DB_USER: "sa"
  DB_PASSWORD: "YourStrongPass123"
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: cemp.local
      paths:
        - path: /
          pathType: Prefix