replicaCount: 1
image:
  repository: docker.io/library/cemp-api
  tag: azurite-fix
  pullPolicy: Never

env:
  - name: BlobStorage__ConnectionString
    value: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;"
  - name: BlobStorage__ContainerName
    value: "employee-photos"
